---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: groww-cluster
  region: us-east-1
nodeGroups:
  - name: groww-workers
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
availabilityZones: ['us-east-1a', 'us-east-1b']